config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "welcome#index"

  resources :users, :only => [:show, :update] do
    get 'upload' => 'users#upload_avatar'
    resources :photos, :except => [:edit, :update]
  end

  resources :photos, :except => [:new, :create] do
    resources :comments, :except => [:show]
    resources :tags, :only => [:new, :create, :destroy]
  end

  resources :tags, :only => [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
  validates :content, :presence => true 
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :tags
  validates :description, :image, :presence => true

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  acts_as_votable
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :photo
  validates :snippet, :presence => true, length: { maximum: 10}

  def find_by_tag
    photos_match = []
    Photo.all.each do |photo|
      photo.tags.each do |tag|
        tag == Tag.find(self.id).snippet
        photos_match.push(photo)
      end
    end
    photos_match
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :photos
  has_many :comments
  
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:name, :email, :password)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:name, :email, :current_password, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @user = User.find(current_user.id)
    @photo = Photo.find(params[:id])
    @comment = @photo.comments.new
  end

  def create
    @user = User.find(current_user.id)
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.new(comment_params)
    if @comment.save
      redirect_to photo_path(@photo)
    else
      flash[:notice] = 'Comment not saved'
      redirect_to photo_path(@photo)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :user_id)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
    p "no!!!!", current_user
    if params[:liked_photo]
      @photo = Photo.find_by_id(params[:liked_photo])
      @photo.liked_by current_user
    end
  end

  def show
    @photo = Photo.find(params[:id])
    @comment = Comment.new
    @tag = Tag.new
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update(photo_params)
      redirect_to photo_path(@photo)
    else
      render :edit
    end
  end

  def new
    @user = current_user
    @photo = Photo.new
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to photos_path
  end

  def create
    @user = current_user
    @photo = @user.photos.new(photo_params)
    if @photo.save
      redirect_to photo_path(@photo)
    else
      render :new
    end
  end

  def likeable
    p "no!!!!"
    @photo = Photo.find_by_id(params[:photo_id])
    @photo.liked_by current_user
    redirect_to photos_path
  end

  private
  def photo_params
  params.require(:photo).permit(:image, :description, :user_id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @matches = @tag.find_by_tag
  end

  def new
    @photo = Photo.find(params[:id])
    @tag = @photo.tags.new
  end

  def create
    @photo = Photo.find(params[:photo_id])
    @tag = @photo.tags.new(tag_params)
    if @tag.save
      redirect_to photo_path(@photo)
    else
      flash[:notice] = 'Comment not saved'
      redirect_to photo_path(@photo)
    end
  end
  private
  def tag_params
    params.require(:tag).permit(:snippet, :photo_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def upload_avatar
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(avatar_params)
    if @user.save
      redirect_to root_path
    else
      render :upload_avatar
    end
  end

  private
  def avatar_params
  params.require(:user).permit(:avatar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/comments/_form.html.erb
<%= render 'layouts/errors', object: @comment %>
<%= form_for [@photo, @comment] do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <% if user_signed_in? && current_user.avatar_file_name %>
    <div class="navbar-header">
      <div class="chip navbar-brand">
        <%= image_tag current_user.avatar, :class => 'img-chip' %>
        <%= current_user.email %>
      </div>
    </div>
    <% end %>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
      <ul class="nav navbar-nav">
        <% if !current_user.avatar_file_name %>
        <li><%= link_to 'Add Avatar Photo', user_upload_path(current_user) %></li>
        <% end %>
        <li><%= link_to 'See your Photos', user_path(current_user) %></li>
        <li><%= link_to 'Upload a Photo', new_user_photo_path(current_user) %></li>
        <li><%= link_to 'See community uploads', photos_path %></li>
      </ul>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
            <li><%= link_to ('Edit profile: '+current_user.name), edit_user_registration_path%></li>
            <li><%= link_to 'Edit Avatar Photo', user_upload_path(current_user) %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
            <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link' %></li>
            <% end %>
          </ul>
        </li>
      </ul>

      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickrClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/photos/_form.html.erb
<%= render 'layouts/errors', object: @photo %>

<%= form_for([@user, @photo], multipart: true) do |f| %>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.label :image %>
    <%= f.file_field :image %>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit 'Upload' %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Edit your post</h1>

<%= render 'form' %>

app/views/photos/index.html.erb
<div class="row">
<% if @photos.length > 0 %>
  <h1>All photos</h1>
  <% @photos.each do |photo|  %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= image_tag photo.image %>
        <div class="caption">
          <h3><%= link_to photo.description, photo_path(photo) %></h3>
          <small>By <%= User.find(photo.user_id).email %></small><br>
          <small>Likes: <%= photo.votes_for.size %> </small>
          <p><%= link_to "Like", :liked_photo => photo.id%> <a href="#" class="btn btn-default" role="button">share</a></p>
          <% if current_user.id == photo.user_id %>
          <p> <%= link_to 'Delete', photo_path(photo), :data => {:confirm => "You sure?", :method => "delete"}  %></p>
            <p> <%= link_to 'Edit', edit_photo_path(photo) %></p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <p>
    You have no photos
  </p>
<% end %>
</div>

app/views/photos/new.html.erb
<h1>new</h1>

<%= render 'form' %>

app/views/photos/show.html.erb
<h1>photo</h1>

<%= image_tag @photo.image %>
<p>
  <%= @photo.description %>
</p>

<hr>

<%= render 'tags/form' %>
<p>
<% @photo.tags.each do |tag| %>
  <%= link_to tag.snippet, tag_path(tag) %> | 
<% end %>
</p>

<%= render 'comments/form' %>
<% @photo.comments.each do |comment| %>
  <p>
    <%= comment.content %>
    <%= User.find(comment.user_id).email %>
  </p>
<% end %>

app/views/tags/_form.html.erb
<%= render 'layouts/errors', object: @tag %>
<%= form_for [@photo, @tag] do |f| %>
  <%= f.hidden_field :user_id, :value => @photo.id %>
  <%= f.label :snippet %>
  <%= f.text_field :snippet %>
  <%= f.submit %>
<% end %>

app/views/tags/index.html.erb
<h1>List of tags</h1>
<ul>
  <% @tags.each do |tag| %>
    <li><%= link_to tag.snippet, tag_path(tag) %></li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Photos that contain <%= @tag.snippet %></h1>
<ul>
  <% @matches.each do |photo| %>
    <li><%= image_tag photo.image %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="row">
<% if current_user.photos.length > 0 %>
  <h1>Your photos</h1>
  <% current_user.photos.each do |photo|  %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= image_tag photo.image %>
        <div class="caption">
          <h3>Description will go here soon</h3>
          <small>By <%= User.find(photo.user_id).email %></small>
          <p><a href="#" class="btn btn-primary" role="button">like</a> <a href="#" class="btn btn-default" role="button">share</a></p>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <p>
    You have no photos
  </p>
<% end %>

</div>

app/views/users/upload_avatar.html.erb
<%= render 'layouts/errors', object: @user %>

<%= form_for(@user, multipart: true) do |f| %>
  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, required: true %>
  </div>
  <div class="actions">
    <%= f.submit 'Upload' %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<% if !user_signed_in? %>
<p>
  Sign in or Sign up under the profile dropdown in the navigation menu
</p>
<% else %>
<p>
  To begin, click an option on the menu
</p>
<% end %>